//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wholesale_store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int id_customer { get; set; }
        public string customer_name { get; set; }
        public string customer_address { get; set; }
        public string cutomer_age { get; set; }
        public int id_product { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
