//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wholesale_store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id_order { get; set; }
        public Nullable<int> id_customer { get; set; }
        public Nullable<int> id_provider { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> count_unit { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Product Product { get; set; }
    }
}
